Moved proto to be only proto files and sources to utils
RoboTeamTwente/roboteam_proto pull request #39
Opened 2020-09-09 07:41 UTC by Yuhanun

Waiting for other repos.

2020-09-09 09:10 UTC, rolfvdhulst requested changes
The cleanest way to do this is to actually keep two things in the Roboteam_Proto repository:
1. The proto files
2. A CMakelists that compiles all of the proto files into a c++ code/ target/library (e.g. roboteam_proto).

Then for the networking in utils you can simply do something like this:
target_link_libraries(networking PUBLIC roboteam_proto).

Note this also helps keep general compile times down as it reduces the need to search in the network headers everytime you link roboteam_proto, and it's a lot more modular / easy to work with.

2020-09-09 10:03 UTC, Yuhanun commented
> The cleanest way to do this is to actually keep two things in the Roboteam_Proto repository:
> 
> 1. The proto files
> 2. A CMakelists that compiles all of the proto files into a c++ code/ target/library (e.g. roboteam_proto).
> 
> Then for the networking in utils you can simply do something like this:
> target_link_libraries(networking PUBLIC roboteam_proto).
> 
> Note this also helps keep general compile times down as it reduces the need to search in the network headers everytime you link roboteam_proto, and it's a lot more modular / easy to work with.

I actually think the way it is right now is how it should be. You shouldn't need a CMakelists.txt in a submodule on a web-UI. I think this is much better, because you can literally just add the proto files as a submodule for anything. 

The whole point of this was so that you don't have non-js stuff in the UI, were we to add the cmakelists there it kinda defeats that purpose.

2020-09-09 10:23 UTC, rolfvdhulst commented
> I actually think the way it is right now is how it should be. You shouldn't need a CMakelists.txt in a submodule on a web-UI. I think this is much better, because you can literally just add the proto files as a submodule for anything.
> 
> The whole point of this was so that you don't have non-js stuff in the UI, were we to add the cmakelists there it kinda defeats that purpose.

Why would you need the CMakelists.txt for the interface? Yes, it would be present in the webrepository, but I'm not saying you should try to do the Protobuf->Javascript conversion using CMake (definitely don't do that).

The point I'm making is that for the c++ parts of our system, having a seperate target for the proto files and for the networking files is nice. I personally think that outweighs having a useless CMakeLists.txt in the directory when you're doing interface development. Now you have to do ugly things with directories/path dependencies in Roboteam_utils to get the proto files to work nicely in the rest of the system, because to compile them you first need to find the repository.
 Compile it as a c++ library where the proto files are defined and it's modular and easier to work with/change in the future. With the current solution you're proposing, also every time someone wants to add/remove a proto file, they have to make a pull request in two repositories instead of one.

2020-09-20 13:25 UTC, rolfvdhulst approved these changes
LGTM, look at the one comment though.
Also, maybe consider deleting large parts of the readme, it's horribly outdated.

2020-09-20 13:25 UTC, rolfvdhulst commented on CMakeLists.txt
> +        # This points to cmake-build-debug/utils/include/utils/networking
This comment is outdated.

2020-09-20 13:52 UTC, Yuhanun commented on CMakeLists.txt
> +        # This points to cmake-build-debug/utils/include/utils/networking
```suggestion
        # This points to cmake-build-debug/proto/include/proto
```

2020-10-01 10:31 UTC, merged